application: facebook-monitor
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /pages
  static_dir: pages

- url: /crab_magnet
  script: fbmonitor.py
  login: admin

- url: /.*
  script: fbmonitor.py

builtins:
- datastore_admin: on
